version: "3"

services:
 postgres:
   restart: always
   image: postgres:latest
   environment:
     POSTGRES_USER: openoversight
     POSTGRES_PASSWORD: terriblepassword
     POSTGRES_DB: openoversight-dev
   volumes:
     - ./container_data/postgres:/var/lib/postgresql/data
   ports:
     - "5432:5432"

 web:
   restart: always
   build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
   environment:
     AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
     AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
     AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
     S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
   volumes:
     - .:/usr/src/open_oversight
   links:
     - postgres:postgres
   expose:
     - "3000"
   working_dir: /usr/src/open_oversight/OpenOversight
   command: /usr/local/bin/gunicorn --reload -w 4 -b 0.0.0.0:3000 app:app
   ports:
     - "3000:3000"
